### PR TITLE
Add gradient-decoding paper and poster

### PR DESCRIPTION
**Pull request by JulioAPeraza**

### CODE REVIEW

**Comment by tsalo** [comment]
lol there are probably a _lot_ of papers and posters to add, since no one's updated the website for like two years

**Comment by JulioAPeraza** [comment]
Yeah, it's going to be a lot. I will start with this one and my posters to check that everything is OK with the website. Then, I will add the papers, talks, posters, and news from the lab. 

We need to move the NiMARE paper from the preprint section, right?

**Comment by tsalo** [comment]
Oh yeah that's right!

btw it might be good to set up dependabot to bump requirements for the website as they are updated.

**Comment by JulioAPeraza** [comment]
That's a great idea! I will add that to the actions in this PR. 
Thanks!

**Pull request merged**
